language: perl6
perl6:
    - latest

virtualenv:
  system_site_packages: true

before_install:
 - sudo apt-get install -qq libportmidi0

install:
    - rakudobrew build-panda
    - panda installdeps .
